Update RELEASE.md instructions to fit current setup
jupyterhub/ltiauthenticator pull request #65
Opened 2021-08-29 16:25 UTC by consideRatio

2021-08-30 21:22 UTC, jgwerner requested changes
Just one minor comment (main vs master reference).

2021-08-30 21:22 UTC, jgwerner commented on RELEASE.md
> +1. Push your two commits to master.
Change to `...commits to main`. There are other references to `master` so will ignore the rest.

2021-08-31 10:20 UTC, consideRatio commented
Updated @jgwerner! Before you merge though, please clarify you understand this is one of two different and exclusive approaches to close #64.

2021-09-01 01:50 UTC, jgwerner approved these changes
LGTM

2021-09-01 01:51 UTC, jgwerner commented
@consideRatio yes it's clear that you can either merge this PR or #64 - I think both are sensible approaches and will let you decide which one to merge. Thanks!

2021-09-01 02:02 UTC, closed without merging

2021-09-01 02:08 UTC, consideRatio commented
Thanks @jgwerner! I merged and cut version 1.1.0 now.